name: Build and Release

on:
  push:
    branches: [main]
    tags:
      - '*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tool
        run: python -m pip install --upgrade pip build

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload artifact (1 day retention)
        uses: actions/upload-artifact@v4
        with:
          name: tablex-${{ matrix.python-version }}-wheel
          path: dist/*.whl
          retention-days: 1

      - name: Upload Release Assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
